name: ABL-Package-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Display python version
      run: python -c "import sys; print(sys.version)"
    - name: Install prolog
      run: |
        sudo apt-get install swi-prolog
    - name: Install package dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
    - name: Install
      run: pip install -v -e .
    - name: Run tests
      run: |
        pytest --cov-config=.coveragerc --cov-report=xml --cov=abl ./tests 
    - name: Publish code coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml